syntax = "proto3";
package examples.book;
option go_package = "github.com/protomux/examples/basic/server/gen/go/proto;bookpb";

service BookService {
  rpc ListBooks (ListBooksRequest) returns (ListBooksResponse);
  rpc CreateBook (CreateBookRequest) returns (CreateBookResponse);
}

message Book {
  int32 id = 1;
  string title = 2;
}

message ListBooksRequest {}

message ListBooksResponse {
  repeated Book books = 1;
}

message CreateBookRequest {
  string title = 1;
}

message CreateBookResponse {
  Book book = 1;
}
